FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env

WORKDIR src/
COPY . .

RUN dotnet restore AnimatedImage/AnimatedImage.csproj
RUN dotnet restore AnimatedImageTest/AnimatedImageTest.csproj
RUN dotnet build   AnimatedImageTest/AnimatedImageTest.csproj
RUN dotnet test    AnimatedImageTest/AnimatedImageTest.csproj
