name: Build libwebp

on:
  workflow_dispatch:

env:
  webpurl: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.6.0.tar.gz
  libwebp: libwebp-1.6.0

jobs:
  download-source:
    runs-on: ubuntu-latest
    steps:
      - name: Download and extract libwebp
        run:  curl -LO ${{ env.webpurl }}

      - name: Cache extracted source
        uses: actions/cache/save@v4
        with:
          path: ${{ env.libwebp }}.tar.gz
          key:  libwebp-source-${{ env.libwebp }}
          enableCrossOsArchive: true

  build-linux:
    needs: download-source
    runs-on: ubuntu-latest
    steps:
      - name: Cache extracted source
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.libwebp }}.tar.gz
          key:  libwebp-source-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: test
        run: |
          mkdir lib-linux-x64
          mkdir lib-linux-arm64
          echo "1" > lib-linux-x64/1
          echo "2" > lib-linux-x64/2
          echo "1" > lib-linux-arm64/1
          echo "2" > lib-linux-arm64/2

      - name: Cache build result
        uses: actions/cache/save@v4
        with:
          path: lib-linux-x64/
          key:  lib-linux-x64-${{ env.libwebp }}
          enableCrossOsArchive: true

      - name: Cache build result
        uses: actions/cache/save@v4
        with:
          path: lib-linux-arm64/
          key:  lib-linux-arm64-${{ env.libwebp }}
          enableCrossOsArchive: true

  build-windows:
    needs: download-source
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, Win32, ARM64]
    steps:
      - name: Cache extracted source
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.libwebp }}.tar.gz
          key:  libwebp-source-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Build libwebp
        run: |
          mkdir lib-win-${{ matrix.arch }}
          echo "1" > lib-win-${{ matrix.arch }}/1
          echo "2" > lib-win-${{ matrix.arch }}/2

      - name: Cache build result
        uses: actions/cache/save@v4
        with:
          path: lib-win-${{ matrix.arch }}/
          key:  lib-win-${{ matrix.arch }}-${{ env.libwebp }}
          enableCrossOsArchive: true

  build-macos:
    needs: download-source
    runs-on: macos-latest
    steps:
      - name: Cache extracted source
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.libwebp }}.tar.gz
          key:  libwebp-source-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Build libwebp
        run: |
          mkdir lib-osx
          echo "1" > lib-osx/1
          echo "2" > lib-osx/2

      - name: Cache build result
        uses: actions/cache/save@v4
        with:
          path: lib-osx/
          key:  lib-osx-${{ env.libwebp }}
          enableCrossOsArchive: true

  package-libs:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Cache linux x64 libs
        uses: actions/cache/restore@v4
        with:
          path: lib-linux-x64/
          key:  lib-linux-x64-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Cache linux arm64 libs
        uses: actions/cache/restore@v4
        with:
          path: lib-linux-arm64/
          key:  lib-linux-arm64-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Cache windows x64 libs
        uses: actions/cache/restore@v4
        with:
          path: lib-win-x64/
          key:  lib-win-x64-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Cache windows x86 libs
        uses: actions/cache/restore@v4
        with:
          path: lib-win-Win32/
          key:  lib-win-Win32-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Cache windows arm64 libs
        uses: actions/cache/restore@v4
        with:
          path: lib-win-ARM64/
          key:  lib-win-ARM64-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Cache osx libs
        uses: actions/cache/restore@v4
        with:
          path: lib-osx/
          key:  lib-osx-${{ env.libwebp }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Collect libs
        run: |
          mkdir libs
          mv lib-linux-x64   libs/linux-x64
          mv lib-linux-arm64 libs/linux-arm64
          mv lib-win-x64     libs/win-x64
          mv lib-win-Win32   libs/win-x86
          mv lib-win-ARM64   libs/win-arm64
          mv lib-osx         libs/osx

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.libwebp }} libraries
          path: libs/
