name: Test Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Windows ${{ matrix.arch }} Test
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
        frm:  [net9.0, net472]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set dotnet path
        run: |
          if ("${{ matrix.arch }}" -eq "x86") {
            echo "DOTNET_EXE=C:\Program Files (x86)\dotnet\dotnet.exe" >> $env:GITHUB_ENV
          } else {
            echo "DOTNET_EXE=dotnet" >> $env:GITHUB_ENV
          }

      - name: Build
        run: |
          &"${{ env:DOTNET_EXE }}" build AnimatedImageTest/AnimatedImageTest.csproj -f ${{ matrix.arch }}

      - name: Test
        run: |
          &"${{ env:DOTNET_EXE}}" test  AnimatedImageTest/AnimatedImageTest.csproj -f ${{ matrix.arch }}
