name: Test Linux ARM64

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run dotnet test in Docker
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --file Dockerfile \
            --output type=cache \
            .
      - name: test
        run: |
          dotnet clean
          dotnet restore
          dotnet test AnimatedImageTest/AnimatedImageTest.csproj
  
