name: Test Mac

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  test-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests
        run: |
          dotnet restore
          dotnet restore AnimatedImageTest/AnimatedImageTest.csproj
          dotnet build   AnimatedImageTest/AnimatedImageTest.csproj
          dotnet test    AnimatedImageTest/AnimatedImageTest.csproj

